Fix dependancy with security hub controls
The following error was occuring -

```
Error: error updating Security Hub Standards Control
(arn:aws:securityhub:us-east-1:532211371847:control/pci-dss/v/3.2.1/PCI.IAM.5):
ResourceNotFoundException: StandardsControl not found
```

This was due to the standards not being in place yet, this change puts a
dependancy on the standard being created.