Add missing resources line
Apply failed with:

```
Error: error creating Backup Selection: InvalidParameterValueException: Invalid backup selection. Either 'ListOfTags' or 'Resources' section must be non-empty.
```